apiVersion: v1
kind: Service
metadata:
  name: feedapirest
spec:
  type: LoadBalancer
  selector:
    app: feedapirestâ€Ž
  ports:
    - name: http
      port: 80         
      targetPort: 8080     
